Adds post-processors to fuel column analysis
arfc/mhtgr350-benchmark pull request #58
Opened 2020-12-08 14:58 UTC by robfairh

fixes #57

(I still have issue #56 in mind, I will address it once I have PRed a bunch of files I have around)

2020-12-30 17:17 UTC, samgdotson requested changes
Same story, all functions need return statements. Try not to repeat yourself.

2021-01-21 16:26 UTC, katyhuff requested changes
PEP8 violations, DRY violations, copy past of entire postprocessing file... . Please reread https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1001745

I recognize that since this is MOOSE related, you're probably following the MOOSE style guide which ignores PEP8. That's fine, but it is a bit annoying to violate PEP8 for all python files even the ones not actually having anything to do with moose... like the py files that generate .geo files... I strongly prefer PEP8 unless this is going to end up in the MOOSE test harness.

2021-01-21 16:26 UTC, katyhuff commented on serpent-moltres/fuel-column/README.md
> +* standard-column-LBP: column of standard fuel assemblies with bottom and top reflectors. It includes lumped burnable poisons in the corners of the hexagon.
Best practice limits line lengths to 80 chars. Please make this a setting in your text editor. 
```suggestion
* standard-column-LBP: column of standard fuel assemblies with bottom and top reflectors. 
It includes lumped burnable poisons in the corners of the hexagon.
```

2021-01-21 16:26 UTC, katyhuff commented on serpent-moltres/fuel-column/README.md
> +* standard-column-LBP: column of standard fuel assemblies with bottom and top reflectors. It includes lumped burnable poisons in the corners of the hexagon.
(I won't make comments everywhere else this happens. Please hardwrap lines through this whole PR.)

2021-01-21 16:26 UTC, katyhuff commented on serpent-moltres/fuel-column/postprocessing.py
> +def plotcsv_groups_collapse(file, save, lim, dire='z'):
This postprocessing.py file is a problem. Reused functions should exist in one and only one place in the repo. No files should be copied, pasted, modified, and replicated across multiple files in a repo. Please review the basic reading in this group Best Practices in Scientific Computing.  https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1001745

2021-01-21 16:26 UTC, katyhuff commented on serpent-moltres/fuel-column/postprocessing.py
> +def plotcsv_groups_collapse(file, save, lim, dire='z'):
(one reason this is bad practice is that here I sit, re-reviewing a file that is *almost* identical to one I have reviewed already twice in a previous PR.)

2021-07-24 16:26 UTC, closed without merging